// Generated by scripts/generate-api.ts — do not edit by hand.
export default {
  index: "Overview",
  sdk: "@parity/product-sdk",
  address: "@parity/product-sdk-address",
  bulletin: "@parity/product-sdk-bulletin",
  "chain-client": "@parity/product-sdk-chain-client",
  contracts: "@parity/product-sdk-contracts",
  crypto: "@parity/product-sdk-crypto",
  host: "@parity/product-sdk-host",
  keys: "@parity/product-sdk-keys",
  logger: "@parity/product-sdk-logger",
  signer: "@parity/product-sdk-signer",
  "statement-store": "@parity/product-sdk-statement-store",
  storage: "@parity/product-sdk-storage",
  tx: "@parity/product-sdk-tx",
  utils: "@parity/product-sdk-utils",
};
