// Generated by scripts/generate-api.ts — do not edit by hand.
export default {
  index: "Overview",
  blake2b256: "blake2b256()",
  "bytes-to-hex": "bytesToHex()",
  "concat-bytes": "concatBytes()",
  "format-balance": "formatBalance()",
  "format-planck": "formatPlanck()",
  "get-balance": "getBalance()",
  "hex-to-bytes": "hexToBytes()",
  keccak256: "keccak256()",
  "parse-to-planck": "parseToPlanck()",
  sha256: "sha256()",
  "utf8-to-bytes": "utf8ToBytes()",
  "account-balance": "AccountBalance",
  "balance-api": "BalanceApi",
  "format-balance-options": "FormatBalanceOptions",
};
