export type MetaEntry =
  | { key: string; label: string }
  | { key: string; value: Record<string, unknown> };

function isValidIdent(s: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s);
}

function serializeKey(key: string): string {
  return isValidIdent(key) ? key : JSON.stringify(key);
}

function serializeValue(value: unknown): string {
  return JSON.stringify(value);
}

export function renderMeta(entries: MetaEntry[]): string {
  const lines: string[] = [
    "// Generated by scripts/generate-api.ts — do not edit by hand.",
    "export default {",
  ];
  for (const e of entries) {
    const key = serializeKey(e.key);
    if ("label" in e) {
      lines.push(`  ${key}: ${JSON.stringify(e.label)},`);
    } else {
      lines.push(`  ${key}: ${serializeValue(e.value)},`);
    }
  }
  lines.push("};");
  return lines.join("\n") + "\n";
}
