export interface MetaEntry {
  key: string;
  label: string;
}

export function renderMeta(entries: MetaEntry[]): string {
  const lines: string[] = ["// Generated by scripts/generate-api.ts — do not edit by hand.", "export default {"];
  for (const e of entries) {
    const keyEscaped = e.key.includes("-") ? JSON.stringify(e.key) : e.key;
    lines.push(`  ${keyEscaped}: ${JSON.stringify(e.label)},`);
  }
  lines.push("};");
  return lines.join("\n") + "\n";
}
