import { existsSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { kebab, packageSlug } from "./lib/kebab.js";
import { isOwnExport } from "./lib/reexports.js";
import { renderPackageOverview, sanitizePackageSummary } from "./lib/render-package.js";
import { pageFor } from "./lib/render-symbol.js";
import { renderMeta, type MetaEntry } from "./lib/write-meta.js";
import { Kind, type Declaration, type Project } from "./lib/types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DOCS_ROOT = resolve(__dirname, "..");
const API_JSON = join(DOCS_ROOT, "generated/api.json");
const API_CONTENT = join(DOCS_ROOT, "content/api");

const GENERATED_MARKER = "generated: true";

function isGeneratedFile(path: string): boolean {
  try {
    const head = readFileSync(path, "utf8").slice(0, 400);
    return head.includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

function removeGeneratedFilesIn(dir: string): void {
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    if (!entry.name.endsWith(".mdx") && entry.name !== "_meta.ts") continue;
    const p = join(dir, entry.name);
    if (entry.name === "_meta.ts") {
      // Only delete _meta.ts if it carries our generator banner.
      const head = readFileSync(p, "utf8").slice(0, 200);
      if (head.includes("Generated by scripts/generate-api.ts")) rmSync(p);
      continue;
    }
    if (isGeneratedFile(p)) rmSync(p);
  }
}

function sectionOrderForMeta(pkg: Declaration, ownFolder: string): MetaEntry[] {
  // Mirrors SECTION_ORDER in render-package.ts, skipping re-exports so they don't appear
  // in the nav at both the umbrella and leaf-package paths.
  const byId = new Map<number, Declaration>();
  (pkg.children ?? []).forEach((c) => byId.set(c.id, c));
  const groupOrder = [
    { title: "Classes", kind: Kind.Class },
    { title: "Functions", kind: Kind.Function },
    { title: "Interfaces", kind: Kind.Interface },
    { title: "Type Aliases", kind: Kind.TypeAlias },
    { title: "Enumerations", kind: Kind.Enum },
    { title: "Variables", kind: Kind.Variable },
  ];
  const seen = new Set<string>();
  const entries: MetaEntry[] = [];
  for (const { title, kind } of groupOrder) {
    const g = (pkg.groups ?? []).find((x) => x.title === title);
    if (!g) continue;
    const items = g.children
      .map((id) => byId.get(id))
      .filter(
        (d): d is Declaration =>
          !!d && d.kind === kind && isOwnExport(d, ownFolder)
      );
    for (const item of items) {
      const slug = kebab(item.name);
      if (seen.has(slug)) continue;
      seen.add(slug);
      const label = kind === Kind.Function ? `${item.name}()` : item.name;
      entries.push({ key: slug, label });
    }
  }
  return entries;
}

function readFrontmatterTitle(path: string): string | null {
  try {
    const head = readFileSync(path, "utf8").slice(0, 600);
    const match = head.match(/^---\s*\n([\s\S]*?)\n---/);
    if (!match) return null;
    const titleMatch = match[1]!.match(/^title:\s*"?([^"\n]+?)"?\s*$/m);
    return titleMatch ? titleMatch[1]!.trim() : null;
  } catch {
    return null;
  }
}

// Curated MDX pages that sit alongside generated ones — include them in the nav
// but after the generator's section-ordered entries. Label from frontmatter title
// if present, otherwise from filename.
function curatedMdxEntries(pkgDir: string, alreadyListed: Set<string>): MetaEntry[] {
  if (!existsSync(pkgDir)) return [];
  const entries: MetaEntry[] = [];
  const files = readdirSync(pkgDir, { withFileTypes: true })
    .filter((e) => e.isFile() && e.name.endsWith(".mdx") && e.name !== "index.mdx")
    .map((e) => e.name)
    .sort();
  for (const file of files) {
    const key = basename(file, ".mdx");
    if (alreadyListed.has(key)) continue;
    const path = join(pkgDir, file);
    const head = readFileSync(path, "utf8").slice(0, 400);
    if (head.includes(GENERATED_MARKER)) continue; // skip generator-produced; already listed
    const title = readFrontmatterTitle(path) ?? key;
    entries.push({ key, label: title });
  }
  return entries;
}

function ownFolderFor(pkg: Declaration): string {
  // Map the package's TypeDoc name to the folder under `product-sdk/packages/`
  // that holds its src. TypeDoc's `sources[].fileName` is relative to the monorepo
  // workspace root (e.g. "sdk/src/...", "signer/dist/..."), so we compare against
  // the first path segment.
  if (pkg.name === "@parity/product-sdk") return "sdk";
  return pkg.name.replace(/^@parity\/product-sdk-/, "");
}

async function writeIfChanged(
  path: string,
  contents: string,
  opts: { requireGeneratedMarker?: boolean } = {}
): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  let existing: string | null = null;
  try {
    existing = readFileSync(path, "utf8");
  } catch {
    // file does not exist yet
  }
  if (existing !== null && opts.requireGeneratedMarker) {
    const head = existing.slice(0, 400);
    if (!head.includes(GENERATED_MARKER)) {
      console.warn(`skip (curated): ${path}`);
      return;
    }
  }
  if (existing === contents) return;
  await writeFile(path, contents, "utf8");
}

async function generateForPackage(pkg: Declaration): Promise<string> {
  const slug = packageSlug(pkg.name);
  const ownFolder = ownFolderFor(pkg);
  const pkgDir = join(API_CONTENT, slug);
  removeGeneratedFilesIn(pkgDir);

  const overview = renderPackageOverview(pkg, ownFolder);
  await writeIfChanged(join(pkgDir, "index.mdx"), overview, { requireGeneratedMarker: true });

  const children = pkg.children ?? [];
  for (const child of children) {
    // Skip re-exports: their canonical page lives in the source package's folder,
    // and the overview links there.
    if (!isOwnExport(child, ownFolder)) continue;
    const page = pageFor(child);
    if (!page) continue;
    await writeIfChanged(join(pkgDir, page.fileName), page.body, {
      requireGeneratedMarker: true,
    });
  }

  const generatedEntries = sectionOrderForMeta(pkg, ownFolder);
  const listed = new Set(generatedEntries.map((e) => e.key));
  listed.add("index");
  const curatedEntries = curatedMdxEntries(pkgDir, listed);

  const meta: MetaEntry[] = [
    { key: "index", label: "Overview" },
    ...generatedEntries,
    ...curatedEntries,
  ];
  // Always overwrite _meta.ts — it's generator-owned. The curated MDX content
  // itself stays untouched; only its nav entry is injected here.
  await writeFile(join(pkgDir, "_meta.ts"), renderMeta(meta), "utf8");

  return slug;
}

function renderApiLandingPage(packages: { slug: string; name: string; summary: string }[]): string {
  const sorted = packages.slice().sort((a, b) => {
    if (a.slug === "sdk") return -1;
    if (b.slug === "sdk") return 1;
    return a.slug.localeCompare(b.slug);
  });
  const lines = [
    "---",
    "generated: true",
    'title: "API Reference"',
    'description: "Reference documentation for every package in @parity/product-sdk."',
    "---",
    "",
    "# API Reference",
    "",
    "Reference documentation for every package in `@parity/product-sdk`. Start with the umbrella package for app-level primitives like `createApp`, or jump into a leaf package for focused functionality.",
    "",
    "| Package | Summary |",
    "| --- | --- |",
  ];
  for (const pkg of sorted) {
    const summary = (pkg.summary || "—").replace(/\s+/g, " ").replace(/\|/g, "\\|");
    lines.push(`| [\`${pkg.name}\`](/api/${pkg.slug}) | ${summary} |`);
  }
  lines.push("");
  return lines.join("\n");
}

async function main(): Promise<void> {
  const project = JSON.parse(readFileSync(API_JSON, "utf8")) as Project;
  if (!project.children || project.children.length === 0) {
    throw new Error("No packages in TypeDoc JSON — did docs:extract run?");
  }

  const packageInfos: { slug: string; name: string; summary: string }[] = [];
  for (const pkg of project.children) {
    const slug = await generateForPackage(pkg);
    const rawSummary = (pkg.comment?.summary ?? [])
      .map((p) => ("text" in p ? (p as { text: string }).text : ""))
      .join("");
    const cleaned = sanitizePackageSummary(rawSummary, pkg.name);
    const firstLine = cleaned.split(/\r?\n/)[0]?.trim() ?? "";
    packageInfos.push({ slug, name: pkg.name, summary: firstLine });
  }
  const slugs = packageInfos.map((p) => p.slug);

  // Root api _meta.ts: intro landing page, "sdk" umbrella, then leaves alphabetically.
  slugs.sort((a, b) => {
    if (a === "sdk") return -1;
    if (b === "sdk") return 1;
    return a.localeCompare(b);
  });
  const rootMeta: MetaEntry[] = [
    { key: "index", label: "Overview" },
    ...slugs.map((slug) => ({
      key: slug,
      label: slug === "sdk" ? "@parity/product-sdk" : `@parity/product-sdk-${slug}`,
    })),
  ];
  await writeFile(join(API_CONTENT, "_meta.ts"), renderMeta(rootMeta), "utf8");
  await writeFile(
    join(API_CONTENT, "index.mdx"),
    renderApiLandingPage(packageInfos),
    "utf8"
  );

  console.log(`Generated API reference for ${slugs.length} package(s).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
