// Generated by scripts/generate-api.ts — do not edit by hand.
export default {
  index: "Overview",
  "create-kv-store": "createKvStore()",
  "kv-store": "KvStore",
  "kv-store-options": "KvStoreOptions",
};
