// Generated by scripts/generate-api.ts — do not edit by hand.
export default {
  index: "Overview",
  "create-app": "createApp()",
  account: "Account",
  app: "App",
  "app-config": "AppConfig",
  "bulletin-api": "BulletinApi",
  "chain-api": "ChainApi",
  "chain-descriptor": "ChainDescriptor",
  "storage-api": "StorageApi",
  "wallet-api": "WalletApi",
};
