// Generated by scripts/generate-api.ts — do not edit by hand.
export default {
  index: "Overview",
  "key-manager": "KeyManager",
  "session-key-manager": "SessionKeyManager",
  "seed-to-account": "seedToAccount()",
  "derived-account": "DerivedAccount",
  "derived-keypairs": "DerivedKeypairs",
  "session-key-info": "SessionKeyInfo",
};
