// Generated by scripts/generate-api.ts — do not edit by hand.
export default {
  index: "Overview",
  configure: "configure()",
  "create-logger": "createLogger()",
  "log-entry": "LogEntry",
  logger: "Logger",
  "logger-config": "LoggerConfig",
  "log-handler": "LogHandler",
  "log-level": "LogLevel",
};
