// Generated by scripts/generate-api.ts — do not edit by hand.
export default {
  index: "Overview",
  "create-chain-client": "createChainClient()",
  "destroy-all": "destroyAll()",
  "get-chain-api": "getChainAPI()",
  "get-client": "getClient()",
  "is-connected": "isConnected()",
  "chain-client-config": "ChainClientConfig",
  "chain-entry": "ChainEntry",
  "chain-client": "ChainClient",
  environment: "Environment",
  "preset-chains": "PresetChains",
};
